classes:
  - 7ev3n
  - APosT
  - Adposhel
  - Agent
  - Agentb
  - Allaple
  - Alueron.gen!J
  - Amonetize
  - Androm
  - Bashlite
  - Bingoml
  - Blacksoul
  - BrowseFox
  - C2LOP.gen!g
  - Convagent
  - Copak
  - Delf
  - Dialplatform.B
  - Dinwod
  - Elex
  - Emotet
  - Escelar
  - Expiro
  - Fakerean
  - Fareit
  - Fasong
  - GandCrab
  - GlobelImposter
  - GootLoader
  - HLLP
  - HackKMS
  - Hlux
  - IcedId
  - Infy
  - Inject
  - Injector
  - InstallCore
  - KRBanker
  - Koadic
  - Kryptik
  - Kwampirs
  - Lamer
  - LemonDuck
  - Loki
  - Lolyda.AA1
  - Lolyda.AA2
  - Mimail
  - MultiPlug
  - Mydoom
  - Neoreklami
  - Neshta
  - NetWireRAT
  - Ngrbot
  - OnlinerSpambot
  - Orcus
  - Padodor
  - Plite
  - PolyRansom
  - QakBot
  - QtBot
  - Qukart
  - REvil
  - Ramdo
  - Regrun
  - Rekt Loader
  - Sakula
  - Salgorea
  - Scar
  - SelfDel
  - Small
  - Snarasite
  - Stantinko
  - Trickpak
  - Upantix
  - Upatre
  - VB
  - VBA
  - VBKrypt
  - VBNA
  - Vilsel
  - Vobfus
  - WBNA
  - Wecod
  - XTunnel
  - Zenpak
  - Zeus

